import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
// importing components
import Header from "@/components/Header";
import MobileNav from "@/components/MobileNav";

const inter = Rubik({
  weight: ["400", "500", "600"],
  subsets:['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
       
        <Header></Header>
        <MobileNav></MobileNav>
  
        {children}
      
        
        </body>
    </html>
  );
}
